services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cuidemjunts-nestjs
    restart: unless-stopped
    depends_on:
      - database
    env_file:
      - .env
    environment:
      - TZ=${TZ}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - NODE_ENV=${NODE_ENV}
    ports:
      - ${WEB_SERVER_PORT}:3000
    working_dir: /usr/src/app
    #command: sh -c "npm install && npm run build && pm2-runtime start pm2.json" # Producci√≥n
    command: sh -c "npm install && npm run db:setup && npm run start:dev" # Desarrollo
    volumes:
      - ./nest_backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - cuidemjunts-network

  database:
    #postgre
    image: postgres:16-alpine
    container_name: cuidemjunts-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - cuidemjunts-network

networks:
  cuidemjunts-network:
    driver: bridge
