name: Build and deploy Node.js app to Azure Web App - cuidemjunts-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio y submódulos
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Instalar y Compilar Backend
        run: |
          cd nest_backend
          npm install
          npm run build

      - name: Preparar artefacto (Solo el contenido de nest_backend)
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          # IMPORTANTE: Al poner la barra al final, subimos el CONTENIDO de la carpeta
          path: nest_backend/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E3A0E87BBBCB4288A8D61CFFF7559290 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EA84F3092A63450B89E4C61569AD39CB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_490025C3295044118F1CA7F3FE530922 }}

      - name: "Desplegar en Azure Web App"
        uses: azure/webapps-deploy@v3
        with:
          app-name: "cuidemjunts-webapp"
          package: .
          # Ahora que nest_backend es la raíz, la ruta es simplemente esta:
          startup-command: "node dist/main.js"
