name: Build and deploy Node.js app to Azure Web App - cuidemjunts-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 1. Checkout del repositorio y submódulos
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: 2. Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: 3. Instalar y Compilar el Backend
        run: |
          cd nest_backend
          npm install
          npm run build

      - name: 4. Empaquetar solo el Backend para Azure
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          # IMPORTANTE: Subimos el CONTENIDO de nest_backend
          # Así Azure verá el package.json y la carpeta dist en la raíz
          path: nest_backend/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: 1. Descargar el código compilado
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: 2. Login en Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E3A0E87BBBCB4288A8D61CFFF7559290 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EA84F3092A63450B89E4C61569AD39CB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_490025C3295044118F1CA7F3FE530922 }}

      - name: 3. Desplegar y forzar arranque
        uses: azure/webapps-deploy@v3
        with:
          app-name: "cuidemjunts-webapp"
          slot-name: "Production"
          package: .
          # Esta es la orden directa de encendido para Azure:
          startup-command: "node dist/main.js"
